import type { CrmSnapshot, Interaction, Partner } from "@/types/crm";

/**
 * Sanitized demonstration data only.
 *
 * Production CRM records, contact details, commercial terms, and correspondence
 * belong in an access-controlled system and must never be committed to this
 * repository or shipped in a client bundle.
 */
export const partners: Partner[] = [
  {
    partnerId: "p-manufacturer-a",
    name: "Manufacturing Partner A",
    type: "current",
    category: "manufacturer",
    status: "active",
    organization: "Demo manufacturing organization",
    contactName: "Manufacturing liaison",
    notes: "Sanitized demo record. Commercial terms and named contacts are stored outside the repository.",
    tags: ["manufacturing", "demo"],
    lastContactDate: "2026-04-15",
    nextFollowUp: "2026-05-15",
    products: ["Coolvex"],
    createdAt: "2026-03-01",
  },
  {
    partnerId: "p-investor-a",
    name: "Investment Partner A",
    type: "current",
    category: "investor",
    status: "active",
    organization: "Demo investment organization",
    contactName: "Investment liaison",
    notes: "Sanitized demo record used to illustrate an active strategic relationship.",
    tags: ["investment", "demo"],
    lastContactDate: "2026-04-10",
    products: [],
    createdAt: "2026-01-01",
  },
  {
    partnerId: "p-academic-a",
    name: "Academic Partner A",
    type: "current",
    category: "academic",
    status: "active",
    organization: "Demo academic organization",
    contactName: "Program liaison",
    notes: "Sanitized demo record used to illustrate an education collaboration.",
    tags: ["education", "demo"],
    nextFollowUp: "2026-05-08",
    products: ["Pure Academy"],
    createdAt: "2026-04-01",
  },
  {
    partnerId: "p-regulator-a",
    name: "Regulatory Authority",
    type: "current",
    category: "government",
    status: "active",
    organization: "Demo regulatory authority",
    notes: "Sanitized demo record. Filing identifiers and source documents are intentionally omitted.",
    tags: ["regulatory", "demo"],
    products: ["Coolvex"],
    createdAt: "2026-02-01",
  },
  {
    partnerId: "p-pharmacy-a",
    name: "Pharmacy Prospect A",
    type: "prospect",
    category: "client",
    status: "pending",
    organization: "Demo pharmacy group",
    contactName: "New-listing team",
    notes: "Sanitized demo lead. Verify the public onboarding process before outreach.",
    tags: ["pharmacy-channel", "new-listing", "demo"],
    nextFollowUp: "2026-05-20",
    products: ["Coolvex"],
    createdAt: "2026-04-20",
  },
  {
    partnerId: "p-research-a",
    name: "Research Partner A",
    type: "prospect",
    category: "academic",
    status: "pending",
    organization: "Demo research organization",
    contactName: "Research liaison",
    notes: "Sanitized demo prospect for a possible research collaboration.",
    tags: ["research", "demo"],
    products: ["INSEBT"],
    createdAt: "2026-04-20",
  },
  {
    partnerId: "p-supplier-a",
    name: "Ingredient Supplier A",
    type: "prospect",
    category: "supplier",
    status: "pending",
    organization: "Demo supplier organization",
    contactName: "Commercial team",
    notes: "Sanitized demo record. Supplier quotes and correspondence are held in private storage.",
    tags: ["supplier", "demo"],
    products: ["Coolvex"],
    createdAt: "2026-04-01",
  },
  {
    partnerId: "p-outreach-a",
    name: "Strategic Outreach A",
    type: "outreach",
    category: "partner",
    status: "dormant",
    organization: "Demo strategic organization",
    notes: "Sanitized demo record for long-range outreach planning.",
    tags: ["outreach", "demo"],
    products: [],
    createdAt: "2026-04-01",
  },
];

export const interactions: Interaction[] = [
  {
    interactionId: "int-demo-001",
    partnerId: "p-manufacturer-a",
    type: "meeting",
    date: "2026-04-15",
    summary: "Demo manufacturing readiness review; confidential details omitted.",
    followUpDate: "2026-05-15",
    createdBy: "Operations",
  },
  {
    interactionId: "int-demo-002",
    partnerId: "p-investor-a",
    type: "meeting",
    date: "2026-04-10",
    summary: "Demo quarterly relationship review; no commercial terms are included.",
    createdBy: "Executive office",
  },
  {
    interactionId: "int-demo-003",
    partnerId: "p-academic-a",
    type: "document",
    date: "2026-04-08",
    summary: "Demo collaboration milestone recorded without source documents or personal data.",
    createdBy: "Program office",
  },
  {
    interactionId: "int-demo-004",
    partnerId: "p-pharmacy-a",
    type: "note",
    date: "2026-04-26",
    summary: "Demo pharmacy onboarding lead; use approved public channels for future contact.",
    followUpDate: "2026-05-20",
    createdBy: "Commercial team",
  },
];

export const crmSnapshot: CrmSnapshot = { partners, interactions };
