import type { CrmSnapshot, Interaction, Partner } from "@/types/crm";

export const partners: Partner[] = [
  // ── Current Partners ──────────────────────────
  {
    partnerId: "p-delta",
    name: "Saudi Delta Company",
    type: "current",
    category: "manufacturer",
    status: "active",
    organization: "Saudi Delta Company (شركة دلتا السعودية)",
    contactName: "—",
    notes: "Manufacturing partner for INSEBT biopesticide. Contract signed ~Mar 7 2026. Revenue split: 60/40 (PA/Delta). Announced publicly via pureadvance.sa blog + LinkedIn on Apr 12, 2026 (written by Ammar Alshehri). Blog title: 'A New Chapter in Biotechnology Manufacturing in Saudi Arabia'. Scope: strengthen local capabilities in biological control solutions. PA role: IP, R&D, commercialization. Delta role: industrial expertise, operational capabilities, manufacturing.",
    tags: ["manufacturing", "bt", "signed"],
    lastContactDate: "2026-04-15",
    nextFollowUp: "2026-05-01",
    dealValue: 0,
    products: ["INSEBT"],
    createdAt: "2026-03-07",
  },
  {
    partnerId: "p-wadi-jeddah",
    name: "Wadi Jeddah",
    type: "current",
    category: "investor",
    status: "active",
    organization: "Wadi Jeddah (KAU)",
    contactName: "Dr. Sattam bin Saud Lingawi",
    notes: "KAU investment arm. Signed Jan 9, 2026. Commercial, scientific, research, training collaboration. Provides: mentorship, legal help, network access. Typical ticket: SAR 500K–5M. Focus: tech, life sciences, cleantech, edtech.",
    tags: ["investment", "incubation", "KAU"],
    lastContactDate: "2026-04-10",
    dealValue: 0,
    products: [],
    createdAt: "2026-01-09",
  },
  {
    partnerId: "p-safea",
    name: "SAFEA",
    type: "current",
    category: "academic",
    status: "active",
    organization: "Saudi Agricultural & Food Export Authority",
    contactName: "Ms. Noha Abdulhafiz Sagga (نهى عبدالحفيظ سقا) — General Manager",
    contactEmail: "n.sagga@wj-safea.com",
    notes: "Education MoU signed Apr 8 2026 (1-year term, 15-day exit). Pure Academy training programs. Dr. Fayez is PA lead. CR: 4030239623. Affiliated with Wadi Jeddah ecosystem.",
    tags: ["MoU", "education", "academy"],
    lastContactDate: "2026-04-08",
    nextFollowUp: "2026-05-08",
    dealValue: 0,
    products: ["Pure Academy"],
    createdAt: "2026-04-08",
  },
  {
    partnerId: "p-accmi",
    name: "ACC Manufacturing Industries",
    type: "current",
    category: "manufacturer",
    status: "active",
    organization: "Arab Chemists Co for Cosmetics and Medical Industries Ltd (ACCMi)",
    contactName: "Basheer Mohamed (CEO)",
    contactEmail: "basheer@accmi.co",
    contactPhone: "+966 5661 31239 / +966 1149 84790 / +966 5464 29039",
    notes: "Full name: Arab Chemists Co for Cosmetics and Medical Industries. Website: accmi.co (WordPress + WooCommerce, live since Dec 2019, last updated Dec 2024). Social: @ACCMI_KSA (Twitter/X), facebook.com/ACCMI.KSA, instagram.com/accmi_ksa. Products: 16+ SKUs — oral care (12 Hour Mouth Wash, APPLEMINT Toothpaste, ORAXO Mouth Wash), skin care (ANURATY Whitening, ASTRA Anti-Aging/Collagen/Lips, Whityx), hair care (Argan Oil, Avocare Shampoo), medical/antiseptic (SMART SEPT IPA 70%, Chlorhexidine 2% & 4%), intimate care (GINA), massage (B-SKEL), nipple care (Argan). Logo file named 'besher-logo'. Coolvex quote: 5,000 units @ 9 SR = 51,750 SR. Pending PO.",
    tags: ["manufacturing", "coolvex", "quote-received"],
    lastContactDate: "2026-04-20",
    nextFollowUp: "2026-05-01",
    dealValue: 51750,
    products: ["Coolvex"],
    createdAt: "2026-04-01",
  },
  {
    partnerId: "p-saip",
    name: "SAIP",
    type: "current",
    category: "government",
    status: "active",
    organization: "Saudi Authority for Intellectual Property",
    notes: "Patent application SA 1020257888 filed Oct 2025 for Coolvex formulation. Under review.",
    tags: ["patent", "IP", "coolvex"],
    lastContactDate: "2025-10-15",
    dealValue: 0,
    products: ["Coolvex"],
    createdAt: "2025-10-15",
  },

  {
    partnerId: "p-sequencive",
    name: "Sequencive Labs",
    type: "current",
    category: "partner",
    status: "active",
    organization: "Sequencive",
    contactName: "Dr. Ayman Karam (CSO)",
    contactEmail: "ayman@sequencive.com",
    contactPhone: "+966 53 604 0121",
    notes: "MENA's leading DeepTech platform. 5 arms: Ventures, Consult, Invest, Labs, Global. Full team: Mohammed AlMadhi (Chairman/CEO, 20+ yrs, 4 exits Europe/Asia), Dr. Ayman Karam (CSO Labs, SGS1 commissioning, robotic inspection Oil&Gas), Anas AlSahli (CTO, RECYCLEE/Drahim AlRajhi/Savvy Games PIF), Amjad AlHamed (Finance Mgr, 7+ yrs, scaled ventures >SAR 100M), Ahmed Hagras (CDO, 10+ yrs product/ops), Asem Al Shamsi (Partner Investment, Oxford MSc, ex-Aramco IPO strategy $20B+), Rakan AlRoqi (Partner Sustainability, CEO RECYCLEE, ex-Saudi AgriFood Tech Alliance SecGen, ex-Misk), Ali Alharbi (Partner Growth, CEO Mohasby, 9+ yrs, CS/AI KSU), Kholoud Aljuhani (Partner Fintech, COO Mohasby), Yousef Alnemri (Partner SportTech, co-founder YANS GYM, 22yr petrochemical), Ahmad Al Hourani (ISO 14005, circular economy). Portfolio: Phyla, RECYCLEE, WOLVEE, REEVA, YANS, Mohasby, MiZax, FLORANOVA. Partners: Imperial College, KACST, KAUST, ARASCO, Google Cloud, KFUPM, SIRC, Jülich. Studio model. Revenue-generating. Also: بشاير الجهني (Comercialization) +966 56 566 4217. Website: www.sequencive.com",
    tags: ["genomics", "sequencing", "R&D", "IP-commercialization", "lab-as-a-service", "venture-builder"],
    products: ["INSEBT"],
    createdAt: "2026-04-28",
  },
  {
    partnerId: "p-phyla",
    name: "Phyla",
    type: "current",
    category: "partner",
    status: "active",
    organization: "Phyla — Feeding the world without consuming it",
    contactName: "Maryah AlOufi (COO)",
    contactEmail: "Maryah@phyla.ws",
    contactPhone: "+966 59 434 6824",
    notes: "Agri-biotech. ماريه العوفي — رئيس العمليات. Co-founded by Maryah AlOufi (MSc Entomology). CEO: Mohammed AlMadhi (also Sequencive CEO). Tech: Black Soldier Fly larvae → alt protein, insect oil, frass (fertilizer), chitin (cosmetic/pharma). Founded 2022 (research), 2023 (incorporated). Funding: SAR 2M grant from MIM. Partners: Tanmiah Food (Feb 2026), Recyclee. Milestones: 2024 pilot, 2025 pre-commercial, 2026 industrial-scale. Sequencive-incubated. Website: www.phyla.ws",
    tags: ["agri-biotech", "sustainability", "sequencive-ventures", "alt-protein"],
    products: [],
    createdAt: "2026-04-28",
  },
  // ── Prospects ─────────────────────────────────
  {
    partnerId: "p-chouayekh",
    name: "Prof. Hichem Chouayekh",
    type: "prospect",
    category: "academic",
    status: "pending",
    organization: "—",
    contactName: "Prof. Hichem Chouayekh",
    notes: "World-renowned Bt/genomics expert. Affiliation: University of Tunis El Manar, LMBA lab. Expertise: Bt biology/genomics, Cry toxin discovery, biopesticide development, Bacillus cereus group comparative genomics. Published in: J. Invertebrate Pathology, Current Microbiology, Applied Microbiology & Biotechnology, Biological Control. h-index ~20-30. Meeting Thu May 1 2026 — Sultan presenting. Goal: scientific advisor / collaboration on INSEBT genomics.",
    tags: ["Bt", "genomics", "advisor", "high-priority"],
    nextFollowUp: "2026-05-01",
    products: ["INSEBT"],
    createdAt: "2026-04-20",
  },
  {
    partnerId: "p-kacst",
    name: "KACST",
    type: "prospect",
    category: "government",
    status: "pending",
    organization: "King Abdulaziz City for Science and Technology",
    notes: "Potential R&D funding and lab access. Target for bioreactor co-funding. Not yet approached.",
    tags: ["funding", "R&D", "bioreactor"],
    products: ["INSEBT"],
    createdAt: "2026-04-01",
  },
  {
    partnerId: "p-nupco",
    name: "NUPCO",
    type: "prospect",
    category: "client",
    status: "dormant",
    organization: "National Unified Procurement Company",
    notes: "Saudi healthcare procurement. Potential distribution channel for biomedicine products. No contact yet.",
    tags: ["procurement", "distribution", "healthcare"],
    products: ["LETHA", "Coolvex"],
    createdAt: "2026-04-01",
  },
  {
    partnerId: "p-monshaat",
    name: "Monsha'at",
    type: "prospect",
    category: "government",
    status: "pending",
    organization: "Saudi SME Authority",
    notes: "SME support programs, grants, and incubation. Apply for biotech track.",
    tags: ["SME", "grants", "incubation"],
    products: [],
    createdAt: "2026-04-01",
  },

  // ── Outreach Targets ──────────────────────────
  {
    partnerId: "p-sabic",
    name: "SABIC",
    type: "outreach",
    category: "partner",
    status: "dormant",
    organization: "Saudi Basic Industries Corporation",
    notes: "Industrial partnership potential — bio-based chemicals and polymers. Long-term target.",
    tags: ["industrial", "bio-chemicals"],
    products: [],
    createdAt: "2026-04-01",
  },
  {
    partnerId: "p-kaust",
    name: "KAUST",
    type: "outreach",
    category: "academic",
    status: "dormant",
    organization: "King Abdullah University of Science and Technology",
    notes: "Research collaboration — synthetic biology, bioinformatics. Potential joint publications and lab access.",
    tags: ["research", "synbio", "bioinformatics"],
    products: ["INSEBT"],
    createdAt: "2026-04-01",
  },
  {
    partnerId: "p-aramco",
    name: "Aramco",
    type: "outreach",
    category: "investor",
    status: "dormant",
    organization: "Saudi Aramco",
    notes: "Aramco entrepreneurship fund / Wa'ed. Biotech-agri alignment. Long-term target.",
    tags: ["investment", "Wa'ed", "agri-tech"],
    products: [],
    createdAt: "2026-04-01",
  },
];

export const interactions: Interaction[] = [
  {
    interactionId: "int-001",
    partnerId: "p-delta",
    type: "document",
    date: "2026-03-07",
    summary: "Manufacturing contract signed (60/40 revenue split).",
    createdBy: "Sultan",
  },
  {
    interactionId: "int-002",
    partnerId: "p-delta",
    type: "meeting",
    date: "2026-04-15",
    summary: "Monthly sync — fermentation scale-up progress review.",
    followUpDate: "2026-05-15",
    createdBy: "Mohammed",
  },
  {
    interactionId: "int-003",
    partnerId: "p-wadi-jeddah",
    type: "document",
    date: "2026-01-09",
    summary: "Partnership & investment agreement signed with KAU.",
    createdBy: "Sultan",
  },
  {
    interactionId: "int-004",
    partnerId: "p-wadi-jeddah",
    type: "meeting",
    date: "2026-04-10",
    summary: "Quarterly review — incubation progress update.",
    createdBy: "Sultan",
  },
  {
    interactionId: "int-005",
    partnerId: "p-safea",
    type: "document",
    date: "2026-04-08",
    summary: "MoU signed for Pure Academy (1-year term). Dr. Fayez leading.",
    createdBy: "Dr. Fayez",
  },
  {
    interactionId: "int-006",
    partnerId: "p-accmi",
    type: "email",
    date: "2026-04-20",
    summary: "Manufacturing quote received: 5,000 units Coolvex @ 9 SR/unit (51,750 SR total).",
    followUpDate: "2026-05-01",
    createdBy: "Mohammed",
  },
  {
    interactionId: "int-007",
    partnerId: "p-saip",
    type: "document",
    date: "2025-10-15",
    summary: "Patent application SA 1020257888 filed for Coolvex formulation.",
    createdBy: "Sultan",
  },
  {
    interactionId: "int-008",
    partnerId: "p-chouayekh",
    type: "meeting",
    date: "2026-05-01",
    summary: "Upcoming meeting — Sultan presenting V4-FINAL slides. Goal: scientific advisor engagement.",
    followUpDate: "2026-05-01",
    createdBy: "Sultan",
  },
];

export const crmSnapshot: CrmSnapshot = { partners, interactions };
